theme: jekyll-theme-cayman
title: [I'm Simrun Buttar!]
description: [I'm currently a sophomore at the University of Michigan, pursuing a B.S.E in Computer Science Engineering. I am actively
looking for an internship in Summer 2019. ]
